### ISSUE TITLE
Collapsible sections

### ISSUE THREAD

**Issue by Kraymer** [mossblaser/recipe_grid#4]
As a user of [programmablerecipes.com](https://programmablerecipes.com/recipes/richardgill/yummy-cookie-recipe?scale=70) I'm used of its collapsable sections and slider to scale recipes.
Implementing the slider in js is out of my capabilities so I went to implement the collapsable sections.

You can find the results at https://kray.me/recipes/poulet_mayo/

![Selection_042](https://github.com/mossblaser/recipe_grid/assets/84227/db8eaad2-eaeb-42b3-a2d8-12ea4c32e4d3)

As it uses bootstrap, I would understand you do not want to introduce that dependency in your rendering.
Please tell me if I should submit a PR or maintain my own fork with that change.

regards

**Comment by mossblaser** [comment]
Hello there! Thanks for your feedback!

# Collapsible sections

I'm afraid as you guessed I'd prefer to keep things minimal for the moment w.r.t things like including bootstrap etc. That said, one of the "to be completed" aspects of recipe grid is the idea of enabling customisation of the HTML templates. If you have experience with making flexible jinja2 templates you might be able to lend some expertise in that space. This would enable you to extend Recipe Grid without a fork.


# Scaling

As for the scaling in the browser, this is something I have thought about but simply put-off out of a wish to avoid writing Javascript. The static site generator, of course, "solves" the problem by generating lots of individually scaled recipes... which is a bit crude.

The main motivator (aside from a general distain for Javascript) is wishing to avoid diplicating or moving the fractional arithmetic and number formatting behaviour into JS. Purely lazy, I'm sure you'll agree, but I would totally be up for merging such a PR if someone wanted to take it on!


# Ingredients-in-method(?)

Separately, I noticed in your example you're putting the ingredient list separately. Whilst you're obviously free to do this if you prefer, one of the things I like about the Recipe Grid presentation is that it can integrate the quantities into the method. As an illustration by changing your source to:

```
## Ingrédients et Instructions
    1 kg poulet  
    1 oignon  
    1 piment  
    4 gousses d’ail  
    1 tbsp gingembre  
    1 tbsp persil  
    5 tbsp mayonnaise  
    1 poivron vert  
 
    assaisonnement vert := écraser(
        poivron vert, 
        persil, 
        gousses d’ail, 
        gingembre, 
        oignon,
        piment
    )

    poulet assaisonné = macérer 1h (
        poulet,
        assaisonnement vert,
        sel,
        poivre,
        paprika
    )
        
    poulet grillé, oignons brûlés = griller au four (
        "poulet assaisonné (40 min)",
        oignons coupés en deux 
    )

    griller au four 15min (
        empaqueter en papillotes (
            débiter en morceaux(poulet grillé),
            mayonnaise,
            oignons brûlés
        )
    )
```

You get the following with the ingredients listed within the grid:

![Sample rendering](https://github.com/mossblaser/recipe_grid/assets/193514/0ef735e1-450f-4f8a-b53a-8ba0c7ac6010)

In this example note that the curly brackets are not needed for typical ingredient quantities and units when presented within a recipe. You also don't need to list ingredients without a quantity (e.g. `sel`).

(NB: I couldn't work out where the `blanc de ciboulette` was used so I removed it in the example above but hopefully you get the idea :)).

Does that make sense? It may also remove the immediate need for collapsible sections in your example: you can read-off the ingredients by just reading down the left-hand-side of the grid!


# People speak things other than English?(!)

I'd also like to apologise for the hopelessly English-only design of Recipe Grid as it stands. As I'm sure you'll have noticed, things like unit names and even the odd bit of the language grammar (e.g. `of the` and `remaining`) completely ignore the existence of other languages. Not to mention to generated web pages. As you can imagine, this was originally built as a tool to scratch a personal itch so other people (much less other languages) never got much of a thought!

If you had some thoughts on how the language ought to be extended (or changed?) to make it multilingual I would be very grateful.

Thanks again and all the best!

**Comment by Kraymer** [comment]
> As for the scaling in the browser, this is something I have thought about but simply put-off out of a wish to avoid writing Javascript. The static site generator, of course, "solves" the problem by generating lots of individually scaled recipes... which is a bit crude.
> The main motivator (aside from a general distain for Javascript) is wishing to avoid diplicating or moving the fractional arithmetic and number formatting behaviour into JS. Purely lazy, I'm sure you'll agree, but I would totally be up for merging such a PR if someone wanted to take it on!

I applied the same kind of reasoning in the past. I have a very back-end approach to things, as shown by [this line](https://github.com/Kraymer/excommito/blob/79ed3528e41f901cfba2abe386e8cc5fb4902c32/_includes/head.html#L55) for example  where i precomputed 365 favicons to have my favicon indicating the date of the last post on the blog.
So don't count on me to write js, but I have to admit here that using a scaler is so much more elegant than generating lots of individually scaled recipes.
  
> Separately, I noticed in your example you're putting the ingredient list separately. Whilst you're obviously free to do this if you prefer, one of the things I like about the Recipe Grid presentation is that it can integrate the quantities into the method. 

Thanks I just started experimenting with your tool, I was not aware of that.

> Does that make sense? It may also remove the immediate need for collapsible sections in your example: you can read-off the ingredients by just reading down the left-hand-side of the grid!

Indeed, problem solved :)


> If you had some thoughts on how the language ought to be extended (or changed?) to make it multilingual I would be very grateful.

Yep I noticed that. In the first integration of the recipes on my blog I used your `recipe-grid-site` tool and had to use `sed` after the pages were generated to replace "for" (keyword triggering scaling) by "pour" (see https://github.com/Kraymer/excommito/commit/473f069712e9d2713042399836f9b2ef6a3d5a48).  
Then I decided to not use your static site builder and have a visually nicer integration by integrating the recipe via an iframe but I had to discard the scaling feature, well...

**Comment by mossblaser** [comment]
Love the favicon trick! :D 

As an alternative to an iframe, if you're only interested in the grid (and not having prose to go with it) you might also want to consider using the [`render_recipe_tree`](https://mossblaser.github.io/recipe_grid/rendering.html#recipe_grid.renderer.html.render_recipe_tree) function to produce a plain HTML tables from a (non-markdown-embedded) recipe source. You can find some CSS for styling these tables [here](https://github.com/mossblaser/recipe_grid/blob/main/recipe_grid/static_site/templates/recipe_tables.css) or, obviously, you could make your own!

As I say, though, having proper templating/theming being a thing would make all of the above redundant anyway as you could tweak the page to fit your needs better anyway... But alas...

**Comment by mossblaser** [comment]
(Whilst you were doing something grotty like that you could render versions at several scales and have some JS swap out which one is shown... But this may all leave a bad taste...)
