### ISSUE TITLE
Having hard time integrating the quantity into the method

### ISSUE THREAD

**Issue by Kraymer** [mossblaser/recipe_grid#5]
I have 2 subrecipes that use sugar (sucre), because of this it seems I cannot define the recipe like so :
~~~
## Instructions

    20 g sucre
    5 oeufs
    

    "jaunes d'oeufs", "blancs d'oeufs" = casser (oeufs)
 
    ile := ajouter(battre("blancs d'oeufs",sel),
                sucre)
                

### Caramel

    80 g sucre
    3 cl eau

                
    caramel := chauffer(sucre, eau)
         
~~~

as it gives me 

![Selection_3220](https://github.com/mossblaser/recipe_grid/assets/84227/6ac63c62-2b5c-46ba-a09b-2bf7e3dbab75)

See how number of eggs is correctly injected but sugar is not.
Do i have to follow https://mossblaser.github.io/recipe_grid/tutorial.html#splitting-recipe-components-up instructions for that case ? I'd prefer to write quantity of sugar for each component separately rather than summing up and then using XX % of sucre

**Comment by mossblaser** [comment]
You can define the sugar twice with different names:

```
first sugar = 20g sugar

...

second sugar = 80g sugar
```

You can reference them later in your recipe using the `first sugar` or `second sugar` names. They'll still show up as just "sugar" in the output. (In fact writing "125g foobar" is just syntactic sugar for "foobar = 125g foobar").

The alternative of starting a new recipe that you mentioned is intended only for when you're describing two independent recipes in one document.

Does that work for you?

**Comment by Kraymer** [comment]
Works beautifully, thanks.
